# Generated by Django 2.0 on 2020-05-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=64, verbose_name='depname')),
                ('workid', models.IntegerField(max_length=64, verbose_name='workid')),
                ('topid', models.IntegerField(max_length=64, verbose_name='topid')),
            ],
            options={
                'db_table': 'u_deppartment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('password', models.CharField(max_length=63, null=True, verbose_name='password')),
                ('role', models.CharField(max_length=10, null=True, verbose_name='role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
