# Generated by Django 2.0 on 2020-05-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=64)),
                ('workid', models.IntegerField()),
                ('topid', models.IntegerField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
